<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('' . $this->translate('Brothers for all'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style_1.css')
                ->prependStylesheet($this->basePath() . '/css/About.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ?>

        <!-- Scripts -->

    </head>
    <body>
        <div class="box">
            <div id="wrapperHeader">
                <div id="header">
                    <img src="../img/logo.png" alt="logo" />

                    <nav>
                        <ul class="dropdown">
                            <li><a href="<?php echo $this->url('about') ?>"><?php echo $this->translate('about') ?></a></li>
                            <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                    About <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">

                                    <li><a href="<?php echo $this->url('about/story') ?>">Story</a></li>
                                    <li><a href="<?php echo $this->url('about/mission') ?>">Mission</a></li>
                                    <li><a href="<?php echo $this->url('about/team') ?>">Team</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                    Get Involved <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">

                                    <!--<li><a href="<?php echo $this->url('getinvolved/volunteer') ?>">Story</a></li>-->
                                    <li><a href="<?php echo $this->url('getinvolved/programs') ?>">Programs</a></li>
                                    <li><a href="<?php echo $this->url('getinvolved/donate') ?>">Donate</a></li>
                                </ul>
                            </li>
                            <li><a href="<?php echo $this->url('store') ?>"><?php echo $this->translate('Store') ?></a></li>
                            <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                    Family <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">

                                    <li><a href="<?php echo $this->url('family/donors') ?>">Donors</a></li>
                                    <li><a href="<?php echo $this->url('family/partners') ?>">Partners</a></li>
                                    <li><a href="<?php echo $this->url('family/gallery') ?>">Gallery</a></li>
                                    <li><a href="<?php echo $this->url('family/advisors') ?>">Tech Advisors</a></li>
                                </ul>
                            </li>
                            <li><a href="<?php echo $this->url('contactus') ?>"><?php echo $this->translate('Contact Us') ?></a></li>
                        </ul>

                    </nav>
                    <section>
                        <div class="about_col_left">
                            <img src="../images/prisoners.jpg"  width="500" height="400"/>
                        </div>
                        <div class="about_col_right">
                            <h1>Our Story</h1>
                            <p>Brothers for All is a spin out of Mothers for All, a non-profit social enterprise that was started in 2008 to provide income generation and entrepreneurship support and training to caregivers of vulnerable children in South Africa and Botswana, where our our work has been supported by Barclays Bank, The World Bank and the EU.</p>
                            <p>In 2010, Mothers for All started working with an award-winning prisoner initiative, called the Group of Hope, which enabled prisoners to change their lives by helping orphans in nearby impoverished communities. We began by designing delivering peer education programmes to cover HIV, STIs and TB in four different prisons. The work was highly successful with our results presented at X1X International AIDS Conference in Washington in 2012 and the Durban AIDS Conference in 2013. We also started an income generation project in the prison which has generated more than R100,000 to support local communities.</p>
                            <p>While working with prisoners trying to turn their lives around, it became clear that aspirational technology skills are the only scalable way to end the cycle of poverty and crime. So in 2014 Brothers for All focused on equipping offenders, ex-offenders and vulnerable youth with aspirational technology and entrepreneurship skills.</p>
                        </div>
                        <div class="clear">
                            <footer>
                                <a href ="https://www.facebook.com/brothersforall?fref=ts" target="_blank"><img src="../img/facebook.png" alt="Mountain View" style="width:30px;height:30px; margin-top :10px;"></a>
                                <a href ="https://twitter.com/brothersforall" target="_blank"><img src="../img/twitter.png" alt="Mountain View" style="width:30px;height:30px; margin-top :10px;" ></a>
                                <a href ="#" target="_blank"><img src="../img/twitter.png" alt="Mountain View" style="width:30px;height:30px; margin-top :10px;" ></a>
                                <h6>
                                    Brothers for All is part of Mothers for All, a charity registered in South Africa and Botswana.<br>
                                    NPO 081-893; PBO 930037032 (18A); MA 327/2008<br>
                                    Copyright © 2015 Mothers For All. Images licensed under Creative Commons by Formgut, Pham Thi Dieu and Bruno Castro from the Noun Project.
                                </h6>

                            </footer>
                    </section>

                </div>
                <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

                <script src="/js/index.js"></script>
                <script src="js/jquery-1.9.1.min.js"></script>
                <script src="js/jquery.slides.min.js"></script>
                <script>
                    $(function () {
                        $("#banner").slidesjs({
                            width: 720,
                            height: 450,
                            play: {
                                active: true,
                                auto: true,
                                interval: 5000,
                                swap: true
                            }
                        });
                    });
                </script>    
            </div> 
        </div>
</html>

