<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle(' ' . $this->translate('Brothers for all'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style_1.css')
                ->prependStylesheet($this->basePath() . '/css/About.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ?>

        <!-- Scripts -->

    </head>
    <body>
        <div class="box">
            <div id="wrapperHeader">
                <div id="header">
                    <img src="../img/logo.png" alt="logo" />

                    <nav>
                        <ul class="dropdown">
                            <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                            <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                About <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">

                                <li><a href="<?php echo $this->url('about/story') ?>">Story</a></li>
                                <li><a href="<?php echo $this->url('about/mission') ?>">Mission</a></li>
                                <li><a href="<?php echo $this->url('about/team') ?>">Team</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                Get Involved <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">

                                <!--<li><a href="<?php echo $this->url('getinvolved/volunteer') ?>">Story</a></li>-->
                                <li><a href="<?php echo $this->url('getinvolved/programs') ?>">Programs</a></li>
                                <li><a href="<?php echo $this->url('getinvolved/donate') ?>">Donate</a></li>
                            </ul>
                        </li>
                         <li><a href="<?php echo $this->url('store') ?>"><?php echo $this->translate('Store') ?></a></li>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                Family <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">

                                <li><a href="<?php echo $this->url('family/donors') ?>">donors</a></li>
                                <li><a href="<?php echo $this->url('family/partners') ?>">partners</a></li>
                                <li><a href="<?php echo $this->url('family/gallery') ?>">Gallery</a></li>
                                <li><a href="<?php echo $this->url('family/advisors') ?>">Tech Advisors</a></li>
                            </ul>
                        </li>
                         <li><a href="<?php echo $this->url('contactus') ?>"><?php echo $this->translate('Contact Us') ?></a></li>
                        </ul>
                    </nav>
                    <div>
		<h3>Tech Advisers</h3>
			<div class="team">
				<a href="hairstyle.html"><img src="../images/alex1.jpg" alt=""></a>
				<b>Alex Lovell Troy</b>
				
				<p>
					Alex Lovell-Troy is the Director of DevOps Transformation at Pythian. A serial entrepreneur, he has helped build and found several companies and mentored many others. As a developer, he contributes regularly to open source projects in many programming languages. He has also taught Linux Systems Administration to the NCSA and built Telescope Control Systems. He speaks regularly to small groups about managing remote developers, virtual currencies, and scaling companies and websites.
				</p>
			</div>
			<div class="team team_middle">
				<a href="hairstyle.html"><img src="../images/joana1.jpg" alt=""></a>
				<b>Joana Picq</b>
				
				<p>
					Joana Picq is a civil engineer turned tech fanatic. She is a partner at Jampp, the leader in user acquisition and user engagement for mobile apps globally, with offices in Argentina, USA, UK, Germany and South Africa. Previous work and ventures have included business development at Microsoft, COO at The Next Women, Entrepreneur in Residence at X.Million Capital Ventures, board advisor for Astia.org and mentor for some of the best accelerators in the world. She also and launched Voyage Privé in Brazil.
				</p>
			</div>
			<div class="team last">
				<a href="hairstyle.html"><img src="../images/damien1.jpg" alt=""></a>
				<b>Damien Scott</b>
				
				<p>
					Damien - who was a founder of Mothers for All, and has played a key role in the development of Brothers for All's strategy and technology programmes - is currently at Stanford University's Graduate School of Business. He was formerly General Manager, in Qatar, for Williams F1 developing and commercialising technologies that have their origins in F1. He is also a co-founder and non-executive director of OneLeap, a startup. He studied physics and at the University of Sydney, where he focused concentrating solar thermal systems.
				</p>
			</div>
		
		</section>
		 <footer>
                        <a href ="https://www.facebook.com/brothersforall?fref=ts" target="_blank"><img src="../img/facebook.png" alt="Mountain View" style="width:30px;height:30px; margin-top :10px;"></a>
                        <a href ="https://twitter.com/brothersforall" target="_blank"><img src="../img/twitter.png" alt="Mountain View" style="width:30px;height:30px; margin-top :10px;" ></a>
                        <a href ="https://brosforall.wordpress.com/" target="_blank"><img src="../img/rss-feeds.png" alt="Mountain View" style="width:30px;height:30px; margin-top :10px;" ></a>
                        <h6>
                            Brothers for All is part of Mothers for All, a charity registered in South Africa and Botswana.<br>
                            NPO 081-893; PBO 930037032 (18A); MA 327/2008<br>
                            Copyright © 2015 Mothers For All. Images licensed under Creative Commons by Formgut, Pham Thi Dieu and Bruno Castro from the Noun Project.
                        </h6>

                    </footer>
	    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
        <script src="/js/index.js"></script>
		<script src="js/jquery-1.9.1.min.js"></script>
	<script src="js/jquery.slides.min.js"></script>
	<script>
	$(function() {
	  $("#banner").slidesjs({
		width: 720,
		height: 450,
		play: {
		  active: true,
		  auto: true,
		  interval: 5000,
		  swap: true
		}
	  });
	});
	</script>
	</div>
  </body>
</html>
