<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('' . $this->translate('Brothers for all'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style_1.css')
                ->prependStylesheet($this->basePath() . '/css/About.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ?>

        <!-- Scripts -->

    </head>
    <body>
        <div class="box">
            <div id="wrapperHeader">
                <div id="header">
                    <img src="../img/logo.png" alt="logo" />

                    <nav>
                        <ul class="dropdown">
                            <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                            <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                    About <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">

                                    <li><a href="<?php echo $this->url('about/story') ?>">Story</a></li>
                                    <li><a href="<?php echo $this->url('about/mission') ?>">Mission</a></li>
                                    <li><a href="<?php echo $this->url('about/team') ?>">Team</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                    Get Involved <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">

                                    <!--<li><a href="<?php echo $this->url('getinvolved/volunteer') ?>">Story</a></li>-->
                                    <li><a href="<?php echo $this->url('getinvolved/programs') ?>">Programs</a></li>
                                    <li><a href="<?php echo $this->url('getinvolved/donate') ?>">Donate</a></li>
                                </ul>
                            </li>
                            <li><a href="<?php echo $this->url('store') ?>"><?php echo $this->translate('Store') ?></a></li>
                            <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                    Family <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">

                                    <li><a href="<?php echo $this->url('family/donors') ?>">Donors</a></li>
                                    <li><a href="<?php echo $this->url('family/partners') ?>">Partners</a></li>
                                    <li><a href="<?php echo $this->url('family/gallery') ?>">Gallery</a></li>
                                    <li><a href="<?php echo $this->url('family/advisors') ?>">Tech Advisors</a></li>
                                </ul>
                            </li>
                            <li><a href="<?php echo $this->url('contactus') ?>"><?php echo $this->translate('Contact Us') ?></a></li>
                        </ul>

                    </nav>
                    <section>
                        <div class="about_col_left">
                            <img src="../images/prisoners.jpg"  width="500" height="400"/>
                        </div>
                        <div class="about_col_right">
                            <h2>1. Donate Money</h2>

                            <p>Your money will help us run more transformative programs in prisons and 
                                communities targeting prisoners, ex-offenders and at-risk youth.</p>

                            <h2>2. Donate Stuff</h2>

                            <p>It’s not always about money. We work in very vulnerable and impoverished
                                communities, so we can put to effective use any of the clutter that is taking
                                up space in your homes, such as: sporting equipment, musical instruments,
                                educational material, books (adults and children), gardening equipment,
                                furniture (chairs, tables, carpets, beds, electronic equipment, toys, clothing
                                and linen. If you have something you'd be able to give, please drop us a line
                                at info@brothersforall.org.</p> 

                            <h2>3. Donate Time</h2>

                            <p>If you have time to give, there are several ways you can help us - especially if
                                you can be a coding mentor! If you're interested, we'd love to hear from you
                                at info@brothersforall.org.</p> 

                        </div>
                        <div class="clear">
                    </section>
                    <footer>
                        <a href ="https://www.facebook.com/brothersforall?fref=ts" target="_blank"><img src="../img/facebook.png" alt="Mountain View" style="width:30px;height:30px; margin-top :10px;"></a>
                        <a href ="https://twitter.com/brothersforall" target="_blank"><img src="../img/twitter.png" alt="Mountain View" style="width:30px;height:30px; margin-top :10px;" ></a>
                        <a href ="#" target="_blank"><img src="../img/twitter.png" alt="Mountain View" style="width:30px;height:30px; margin-top :10px;" ></a>
                        <h6>
                            Brothers for All is part of Mothers for All, a charity registered in South Africa and Botswana.<br>
                            NPO 081-893; PBO 930037032 (18A); MA 327/2008<br>
                            Copyright © 2015 Mothers For All. Images licensed under Creative Commons by Formgut, Pham Thi Dieu and Bruno Castro from the Noun Project.
                        </h6>

                    </footer>
                </div>
                <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

                <script src="/js/index.js"></script>
                <script src="js/jquery-1.9.1.min.js"></script>
                <script src="js/jquery.slides.min.js"></script>
                <script>
                    $(function () {
                        $("#banner").slidesjs({
                            width: 720,
                            height: 450,
                            play: {
                                active: true,
                                auto: true,
                                interval: 5000,
                                swap: true
                            }
                        });
                    });
                </script>    
            </div> 
        </div>
</html>

