<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle(' ' . $this->translate('Brothers for all'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style_1.css')
                ->prependStylesheet($this->basePath() . '/css/Gallery.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ?>

        <!-- Scripts -->

    </head>
    <<body>
        <div class="box">
            <div id="wrapperHeader">
                <div id="header">
                    <img src="../img/logo.png" alt="logo" />
                </div>
                <nav>
                    <ul class="dropdown">
                        <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                About <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">

                                <li><a href="<?php echo $this->url('about/story') ?>">Story</a></li>
                                <li><a href="<?php echo $this->url('about/mission') ?>">Mission</a></li>
                                <li><a href="<?php echo $this->url('about/team') ?>">Team</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                Get Involved <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">

                                <!--<li><a href="<?php echo $this->url('getinvolved/volunteer') ?>">Volunteer</a></li>-->
                                <li><a href="<?php echo $this->url('getinvolved/programs') ?>">Programs</a></li>
                                <li><a href="<?php echo $this->url('getinvolved/donate') ?>">Donate</a></li>
                            </ul>
                        </li>
                        <li><a href="<?php echo $this->url('store') ?>"><?php echo $this->translate('Store') ?></a></li>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                Family <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">

                                <li><a href="<?php echo $this->url('family/donors') ?>">Donors</a></li>
                                <li><a href="<?php echo $this->url('family/partners') ?>">Partners</a></li>
                                <li><a href="<?php echo $this->url('family/gallery') ?>">Gallery</a></li>
                                <li><a href="<?php echo $this->url('family/advisors') ?>">Tech Advisors</a></li>
                            </ul>
                        </li>
                        <li><a href="<?php echo $this->url('contactus') ?>"><?php echo $this->translate('Contact Us') ?></a></li>
                    </ul>

                </nav>
                <section>
                    <h1>Gallery</h1>
                    Brothers for all it’s a place where it’s all about ensuring that we live in an environment that we are able to learn and grow from.  Our gallery gives you th feel of showing you of how united we are about helping each other grow.
                    <div class="wrap">
                        <div class="image-container">
                            <div class="img img-1">
                                <div class="mask"></div>
                                <div class="single">
                                    <a href="img/001.png" rel="lightbox"><img src="../img/001.fw.png" alt=""></a>
                                </div>
                            </div>	
                            <div class="img img-1">
                                <div class="mask"> </div>
                                <div class="single">
                                    <a href="../img/002.png" rel="lightbox"><img src="../img/002.png" alt=""></a>
                                </div>
                            </div>	
                            <div class="img img-1">
                                <div class="mask"> </div>
                                <div class="single">
                                    <a href="../img/003.png" rel="lightbox"><img src="../img/003.png" alt=""></a>
                                </div>
                            </div>	
                            <div class="img img-1">
                                <div class="mask"> </div>
                                <div class="single">
                                    <a href="../img/004.png" rel="lightbox"><img src="../img/004.png" alt=""></a>
                                </div>
                            </div>	
                            <div class="img img-1">
                                <div class="mask"> </div>
                                <div class="single">
                                    <a href="../img/005.png" rel="lightbox"><img src="../img/005.png" alt=""></a>
                                </div>
                            </div>	
                            <div class="img img-1">
                                <div class="mask"> </div>
                                <div class="single">
                                    <a href="../img/006.png" rel="lightbox"><img src="../img/006.png" alt=""></a>
                                </div>
                            </div>	

                            <div class="img img-1">
                                <div class="mask"> </div>
                                <div class="single">
                                    <a href="../img/007.png" rel="lightbox"><img src="../img/007.png" alt=""></a>
                                </div>
                            </div>	
                            <div class="img img-1">
                                <div class="mask"> </div>
                                <div class="single">
                                    <a href="../img/008.png" rel="lightbox"><img src="../img/008.png" alt=""></a>
                                </div>
                            </div>

                            <div class="img img-1">
                                <div class="mask"> </div>
                                <div class="single">
                                    <a href="../img/009.png" rel="lightbox"><img src="../img/009.png" alt=""></a>
                                </div>
                            </div>

                            <footer>
                                <a href ="https://www.facebook.com/brothersforall?fref=ts" target="_blank"><img src="../img/facebook.png" alt="Mountain View" style="width:30px;height:30px; margin-top :10px;"></a>
                                <a href ="https://twitter.com/brothersforall" target="_blank"><img src="../img/twitter.png" alt="Mountain View" style="width:30px;height:30px; margin-top :10px;" ></a>
                                <a href ="https://brosforall.wordpress.com/" target="_blank"><img src="../img/twitter.png" alt="Mountain View" style="width:30px;height:30px; margin-top :10px;" ></a>
                                <h6>Brothers for All is part of Mothers for All, a charity registered in South Africa and Botswana.<br>
                                    NPO 081-893; PBO 930037032 (18A); MA 327/2008<br>
                                    Copyright © 2015 Mothers For All. Images licensed under Creative Commons by Formgut, Pham Thi Dieu and Bruno Castro from the Noun Project.</h6><div id="icons"><a href="three-column.html">

                                        </footer>
                                </div>
                                <div class="clear"></div>

                                </section>

                        </div>

                    </div>

                    <script src='js/jquery.min.js'></script>
                    <script src="/js/index.js"></script>
                    <script src="js/jquery-1.9.1.min.js"></script>

                    <script>
                        jQuery(document).ready(function ($) {
                            //Reference http://www.jssor.com/development/slider-with-slideshow-jquery.html
                            //Reference http://www.jssor.com/development/tool-slideshow-transition-viewer.html

                            var _SlideshowTransitions = [
                                //Fade
                                {$Duration: 3000, $Opacity: 2}
                            ];

                            var options = {
                                $SlideDuration: 500, //[Optional] Specifies default duration (swipe) for slide in milliseconds, default value is 500
                                $DragOrientation: 3, //[Optional] Orientation to drag slide, 0 no drag, 1 horizental, 2 vertical, 3 either, default value is 1 (Note that the $DragOrientation should be the same as $PlayOrientation when $DisplayPieces is greater than 1, or parking position is not 0)
                                $AutoPlay: true, //[Optional] Whether to auto play, to enable slideshow, this option must be set to true, default value is false
                                $AutoPlayInterval: 1500, //[Optional] Interval (in milliseconds) to go for next slide since the previous stopped if the slider is auto playing, default value is 3000
                                $SlideshowOptions: {//[Optional] Options to specify and enable slideshow or not
                                    $Class: $JssorSlideshowRunner$, //[Required] Class to create instance of slideshow
                                    $Transitions: _SlideshowTransitions, //[Required] An array of slideshow transitions to play slideshow
                                    $TransitionsOrder: 1, //[Optional] The way to choose transition to play slide, 1 Sequence, 0 Random
                                    $ShowLink: true                                    //[Optional] Whether to bring slide link on top of the slider when slideshow is running, default value is false
                                }
                            };

                            var jssor_slider1 = new $JssorSlider$("slider1_container", options);

                        });
                    </script>
            </div>
            <script type="text/javascript" src="js/jquery-1.9.1.min.js"></script>
            <script src="js/modernizr.js" type="text/javascript"></script>
            <script type="text/javascript" src="js/jssor.js"></script>
            <script type="text/javascript" src="js/jssor.slider.js"></script>
            <script src="lightboxjs/jquery-1.7.2.min.js"></script>
            <script src="lightboxjs/lightbox.js"></script>
    </body>
</html>
