<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle(' ' . $this->translate('Brothers for all'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
         echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style_1.css')
               
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ?>

        <!-- Scripts -->

    </head>
    <body>
        <div class="box">
            <div id="wrapperHeader">
                <div id="header">
                    <img src="../img/logo.png" alt="logo" />
                </div>
                    <nav>
                        <ul class="dropdown">
                            <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                            <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                    About <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">

                                    <li><a href="<?php echo $this->url('about/story') ?>">Story</a></li>
                                    <li><a href="<?php echo $this->url('about/mission') ?>">Mission</a></li>
                                    <li><a href="<?php echo $this->url('about/team') ?>">Team</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                    Get Involved <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">

                                    <!--<li><a href="<?php echo $this->url('getinvolved/volunteer') ?>">Story</a></li>-->
                                    <li><a href="<?php echo $this->url('getinvolved/programs') ?>">Programs</a></li>
                                    <li><a href="<?php echo $this->url('getinvolved/donate') ?>">Donate</a></li>
                                </ul>
                            </li>
                            <li><a href="<?php echo $this->url('store') ?>"><?php echo $this->translate('Store') ?></a></li>
                            <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                    Family <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">

                                    <li><a href="<?php echo $this->url('family/donors') ?>">Donors</a></li>
                                    <li><a href="<?php echo $this->url('family/partners') ?>">Partners</a></li>
                                    <li><a href="<?php echo $this->url('family/gallery') ?>">Gallery</a></li>
                                    <li><a href="<?php echo $this->url('family/advisors') ?>">Tech Advisors</a></li>
                                </ul>
                            </li>
                            <li><a href="<?php echo $this->url('contactus') ?>"><?php echo $this->translate('Contact Us') ?></a></li>
                        </ul>

                    </nav>
                
                
                    <section>
                        <div class="about_col_left">
                            <img src="../img/prisonRehab.jpg" class="first_img" width="500" height="350" />
                            <br/> <br/>
                            <img src="../img/comunityUplifment.jpg" class="first_img" width="500" height="350" />
                            <br/> <br/>
                            <img src="../img/coding.jpg" width="500" height="350" />
                        </div>
                        <div class="about_col_right">
                            <h1>Prison Rehabilitation</h1>
                            <p>Brothers for All members are all expected to help build and strengthen their communities in exchange for job skills training. Once they are enrolled on the coding programme they automatically become part of our Playing it Safe peer education project as well as our income generation programme.</p>
                            <p>Brothers for All was invited to present the results of our highly successful HIV programme at the International AIDS Conference in Washington in 2012 and the South African AIDS Conference in 2013. The Group of Hope offenders have raised over R100 000 through the paper bead project, which they have used to support community projects focusing on vulnerable children and the elderly. They have also travelled to prisons around the country to teach offenders these skills and have won several awards for this work. We have received permission to teach offenders to code which will give them high-value job skills and help to reduce the risk 
                                of them re-offending on their release due to lack of work opportunities.</p>
                            <h1>Community Upliftment</h1>
                            <p>Brothers for All members are all expected to help build and strengthen their communities in exchange for job skills training. Once they are enrolled on the coding programme they automatically become part of our Playing it Safe peer education project as well as our income generation programme.</p>
                            <p>The latter helps to generate funds for our upliftment initiatives that focus on: orphans and vulnerable children; advocacy and awareness events around gender violence, substance abuse and crime; and constructive engagement with other non-profits, community initiatives and government departments (such as the Departments of Health, Social Development and Community Corrections and the South African Police Service).</p>
                            <h1>How can I help</h1>
                            <p>The best way to help is either by buying our products - visit our Store - or by donating stuff you no longer need which can be put to good use by the very poor children we support - visit our Donate page.</p>
                            <h1>Coding and Startups</h1>
                            <p>Youth unemployment is more than 80% in the communities in which we work. The lure of crime, which pays better than most jobs - if you're lucky enough to get a job - is powerful. Coding and entrepreneurship offer a pathway to well-paying stimulating jobs and a global marketplace.</p>
                            <p>Several years ago the Brothers for All project team, who were working on a prison programme, were asked the following question by an offender: What should I be learning now that will help me get a job when I am released in five years’ time? This got us thinking.</p>
                            

                        </div>
                        <div class="clear"/>
                    </section>
                    <footer>
                        <a href ="https://www.facebook.com/brothersforall?fref=ts" target="_blank"><img src="../img/facebook.png" alt="Mountain View" style="width:30px;height:30px; margin-top :10px;"></a>
                        <a href ="https://twitter.com/brothersforall" target="_blank"><img src="../img/twitter.png" alt="Mountain View" style="width:30px;height:30px; margin-top :10px;" ></a>
                        <a href ="https://brosforall.wordpress.com/" target="_blank"><img src="../img/rss-feeds.png" alt="Mountain View" style="width:30px;height:30px; margin-top :10px;" ></a>
                        <h6>
                            Brothers for All is part of Mothers for All, a charity registered in South Africa and Botswana.<br>
                            NPO 081-893; PBO 930037032 (18A); MA 327/2008<br>
                            Copyright © 2015 Mothers For All. Images licensed under Creative Commons by Formgut, Pham Thi Dieu and Bruno Castro from the Noun Project.
                        </h6>

                    </footer>
                    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

                    <script src='js/jquery.min.js'></script>
            <script src="/js/index.js"></script>
            <script src="js/jquery-1.9.1.min.js"></script>
            <script src="js/jssor.slider.js"></script>
            <script src="js/jssor.js"></script>



                    </div>
                    </body>
                    </html>
             
           