<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('' . $this->translate('Brothers for all'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style_1.css')
                ->prependStylesheet($this->basePath() . '/css/Gallery.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ?>

        <!-- Scripts -->

    </head>
    <body>
        <div class="box">
            <div id="wrapperHeader">
                <div id="header">
                    <img src="img/logo.png" alt="logo" />

                    <nav>
                        <ul class="dropdown">
                            <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                            <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                    About <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">

                                    <li><a href="<?php echo $this->url('about/story') ?>">Story</a></li>
                                    <li><a href="<?php echo $this->url('about/mission') ?>">Mission</a></li>
                                    <li><a href="<?php echo $this->url('about/team') ?>">Team</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                    Get Involved <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">

                                    <!--<li><a href="<?php echo $this->url('getinvolved/volunteer') ?>">Story</a></li>-->
                                    <li><a href="<?php echo $this->url('getinvolved/programs') ?>">Programs</a></li>
                                    <li><a href="<?php echo $this->url('getinvolved/donate') ?>">Donate</a></li>
                                </ul>
                            </li>
                            <li><a href="<?php echo $this->url('store') ?>"><?php echo $this->translate('Store') ?></a></li>
                            <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                    Family <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">

                                    <li><a href="<?php echo $this->url('family/donors') ?>">Donors</a></li>
                                    <li><a href="<?php echo $this->url('family/partners') ?>">Partners</a></li>
                                    <li><a href="<?php echo $this->url('family/gallery') ?>">Gallery</a></li>
                                    <li><a href="<?php echo $this->url('family/advisors') ?>">Tech Advisors</a></li>
                                </ul>
                            </li>
                            <li><a href="<?php echo $this->url('contactus') ?>"><?php echo $this->translate('Contact Us') ?></a></li>
                        </ul>

                    </nav>

               
<h1>Thank You!</h1>

<p>
    <div class="alert alert-success">
        We will respond to the E-mail address you have provided.
    </div>
</p>
<h1>Thank You!</h1>

<p>
    <div class="alert alert-success">
        We will respond to the E-mail address you have provided.
    </div>
</p>
<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

        <script src="/js/index.js"></script>
		<script src="js/jquery-1.9.1.min.js"></script>
	<script src="js/jquery.slides.min.js"></script>
	<script>
	$(function() {
	  $("#banner").slidesjs({
		width: 720,
		height: 450,
		play: {
		  active: true,
		  auto: true,
		  interval: 5000,
		  swap: true
		}
	  });
	});
	</script>
        </div>
            </body>
            </html>